[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TAD3"
authors = [{name = "Communtiy", email = "hello@blocktransfer.dev"}]
dynamic = ["version", "description"]
